#!/usr/bin/env bash
red_font='\e[0;31m'
green_font='\e[0;32m'
no_decoration='\e[0m'


docker ps -a  --format "table {{.Names}}\t{{.Ports}} {{.State}}" |\
  sed -E 's/ [0-9-]*?\/[a-z]{3}(,|$| )//g' |\
  sed -E "s/[0\.]{7}(:[0-9-]*?)->[0-9-]*?(\/tcp|)/\1/g" |\
  sed -E 's/ :[0-9-]*?\/udp(,|$| )//g' |\
  sed -E "s/(.*?)exited.*?$/$(printf "${red_font}")[✗] \1$(printf "${no_decoration}")/g" |\
  sed -E "s/(.*?)running.*?$/$(printf "${green_font}")[✓]$(printf "${no_decoration}") \1/g" |\
  sed -E '1d' |\
  sort

