#!/usr/bin/env bash

for str in one two three;
  do echo $str;
done
# # # >  ./fortest
# # # one
# # # two
# # # three

input="one two three"
for str in "$input";
  do echo $str;
done
# # >  ./fortest
# # one two three

input="one,two,three"
for str in ${input//,/ };
  do echo $str;
done
# # > ./fortest
# # one
# # two
# # three

input="one two three"
for str in $(echo $input | xargs);
  do echo $str;
done
# # > ./fortest
# # one
# # two
# three