#!/usr/bin/env bash

# UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

if [[ $1 == "--logo" ]]; then
    logo="$(tput setaf 2)
       .~~.   .~~.
      '. \ ' ' / .'$(tput setaf 1)
       .~ .~~~..~.
      : .~.'~'.~. :
     ~ (   ) (   ) ~
    ( : '~'.~.'~' : )
     ~ .~ (   ) ~. ~
      (  : '~' :  )
       '~ .~~~. ~'
           '~'
    $(tput sgr0)"

    echo "$logo"
fi

# get the load averages
# read one five fifteen rest < /proc/loadavg

# echo "$(tput setaf 2)
# `date +"%A, %e %B %Y, %r"`
# `uname -srmo`

# $(tput sgr0)- Uptime.............: ${UPTIME}
# $(tput sgr0)- Memory.............: `free | grep Mem | awk '{print $3/1024}'` MB (Used) / `cat /proc/meminfo | grep MemTotal | awk {'print $2/1024'}` MB (Total)
# $(tput sgr0)- Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
# $(tput sgr0)- Running Processes..: `ps ax | wc -l | tr -d " "`
# $(tput sgr0)- IP Addresses.......: `hostname -I | /usr/bin/cut -d " " -f 1` and `wget -q -O - http://icanhazip.com/ | tail`
# $(tput sgr0)- External HDD.......: `hostname -I | /usr/bin/cut -d " " -f 1` and `wget -q -O - http://icanhazip.com/ | tail`


# $(tput sgr0)"

/home/pi/Scripts/systemstatus

/home/pi/.nvm/versions/node/v16.14.2/bin/reddit -n
