#!/usr/bin/env bash

# Example output:
# [✓] Pihole is alive (:80)
# [✗] node-red is down (:1880)
# [✓] Wireguard is alive (:51820)
# [✓] Homebridge is alive (:8581)
# [✓] Internet connection is alive

function checkStatus {
  local var NAME="$1"
  local var COMMAND="$2"
  local var PORT="$3"
  local var ADDITIONAL_CMD="$4"

  ${COMMAND} &> /dev/null
  local var STATUS=$?

  if [[ ${STATUS} -eq "0" ]]; then
    printf "\e[0;32m[✓]\e[0m ${NAME} is alive"
    [[ ! -z $PORT ]] && printf " (:${PORT})"
    if [[ ! -z $ADDITIONAL_CMD ]]; then
      eval "$ADDITIONAL_CMD | xargs echo -n"
    fi
    printf "\n"
  else
    printf "\e[0;31m[✗] ${NAME} is down"
    [[ ! -z $PORT ]] && printf " (:${PORT})"
    printf "\e[0m\n"
  fi
}

checkStatus 'Pihole' 'pihole status' '80' 'pihole status | grep --color=none "[✗].*"'
checkStatus 'node-red' 'nc -vz 10.1.0.166 1880' '1880'
checkStatus 'Wireguard' 'sudo wg show' '51820'
checkStatus 'Homebridge' 'nc -vz 10.1.0.166 8581' '8581'
checkStatus 'Internet connection' 'ping -c 1 -W 1 8.8.8.8'
